# Shared package loads for the write-up, Shiny app, and sourced R scripts.
library(shiny)
library(bslib)
library(knitr)
library(ggplot2)
library(dplyr)
library(readr)
library(tidyverse)
library(ISOcodes)
library(tidytext)
library(Matrix)
library(kableExtra)
library(corrplot)
library(igraph)
library(ggraph)
library(widyr)
